// Automatically generated by astro-icon
// 14ab51ff8b7000aa0ee7192f85d50e52b618e9d1eccfced34cc6531973e5e224

declare module "virtual:astro-icon" {
    export type Icon = "course" | "email" | "external" | "github" | "linkedin" | "phone";
}
